### PR TITLE
GZIP Sensibo API Posts

### PR DESCRIPTION
**Pull request by eksuri**
This should allow the user to make 10 request per minute instead of 5.

### CODE REVIEW

**Comment by eksuri** [comment]
There is also a post in GetToken but I have not tested modifying that, could add that if wanted.

**Comment by benwebbbenwebb** [comment]
Thanks @eksuri 

Will take a look over the weekend.

Seems this is related to #132, right? If you’re having issues, are you using the latest alpha or on the release version of the plugin?

**Review by nadavge — APPROVED** [review]

**Comment by eksuri** [comment]
Yes this change is related to the 429 rate limiting that users have been reporting in #132 #138 #140.

The retry logic is a good addition but I have found that this fix here mitigated the issue for me I am under the increased throttling threshold. I have been running this change locally for about a month now.

**Comment by eksuri** [comment]
Sorry to reset approval

**Review by benwebbbenwebb — APPROVED** [review]
Looks simple enough, will merge to master and test it out locally

Edit / note: I had to make a small style change to satisfy the stylistic linter

**Pull request merged**
