### PR TITLE
Add option to filter devices by locations

### PR DESCRIPTION
**Pull request by asafalima**

### CODE REVIEW

**Comment by nitaybz** [comment]
Thanks for the PR... can you describe why do we need both include and exclude?
If I choose location to exclude isn't it including everyone else? And the other way around....

I suggest sticking with one, include or exclude... less configurations, less trouble :)

**Comment by asafalima** [comment]
Thanks for the quick review @nitaybz.
I wanted to give the user the maximum flexibility to only include certain locations or excluding others.
I agree with you, let's add it when it'll be needed :)

**Comment by asafalima** [comment]
Hi @nitaybz, can you review the changes and merge+release a new version if there are no more changes to make?
Thanks

**Comment by nitaybz** [comment]
Thanks for the reminder... Your feature is available on version 2.0.21.
And thanks for collaborating :)

**Pull request merged**
