### PR TITLE
Do not update climate react state (neither locally, nor remotely) if enableClimateReactAutoSetup is "false"

### PR DESCRIPTION
**Pull request by seidnerj**

### CODE REVIEW

**Comment by benwebbbenwebb** [comment]
Thanks @seidnerj 

This is exactly what I was thinking.

I personally would have passed `enableClimateReactAutoSetup` via the device object (e.g. added it in AirConditioner.js) but it’s basically the same.

**Comment by seidnerj** [comment]
Any plans to do a release with the changes we've implemented?

**Comment by benwebbbenwebb** [comment]
Sure, can do @seidnerj 

Have you had an opportunity to test out the alpha and ensure it’s working as expected?

**Comment by seidnerj** [comment]
Yes, as far as I can tell everything works as it should, though I'm sure I haven't gone over every little feature of the plugin.

**Pull request merged**
